from __future__ import annotations

from d2lut.models import PriceEstimate


class D2RFilterExporter:
    """Export value tiers for D2R built-in loot filter rules.

    Note: exact `fg` suffix injection into item labels is done via
    D2RJsonFilterExporter (item-names.json). This exporter generates
    a preview/summary of price tiers.
    """

    def export(self, price_index: dict[str, PriceEstimate]) -> str:
        """Generate a summary of price tiers for analysis/preview."""
        lines = [
            "// d2lut generated price tiers",
            "// Generated by D2RFilterExporter",
            "// Format: canonical_id: ~price FG (confidence)",
            "",
        ]
        
        # Sort by FG descending
        sorted_items = sorted(price_index.items(), key=lambda kv: kv[1].estimate_fg, reverse=True)
        
        # Track current tier for section headers
        current_tier = None
        
        for key, est in sorted_items:
            fg = est.estimate_fg
            conf = est.confidence
            
            # Determine tier
            if fg >= 1000:
                tier = "GG"
            elif fg >= 200:
                tier = "HIGH"
            elif fg >= 50:
                tier = "MID"
            elif fg >= 10:
                tier = "LOW"
            else:
                tier = "TRASH"
            
            # Add section header when tier changes
            if tier != current_tier:
                current_tier = tier
                tier_thresholds = {
                    "GG": "1000+ FG",
                    "HIGH": "200-999 FG",
                    "MID": "50-199 FG",
                    "LOW": "10-49 FG",
                    "TRASH": "<10 FG",
                }
                lines.append(f"// === {tier} TIER ({tier_thresholds[tier]}) ===")
            
            lines.append(f"// [{tier}] {key}: ~{fg:.0f} FG ({conf})")
        
        lines.extend([
            "",
            "// === TIER SUMMARY ===",
            f"// Total items: {len(price_index)}",
            f"// GG (1000+): {sum(1 for e in price_index.values() if e.estimate_fg >= 1000)}",
            f"// HIGH (200-999): {sum(1 for e in price_index.values() if 200 <= e.estimate_fg < 1000)}",
            f"// MID (50-199): {sum(1 for e in price_index.values() if 50 <= e.estimate_fg < 200)}",
            f"// LOW (10-49): {sum(1 for e in price_index.values() if 10 <= e.estimate_fg < 50)}",
            f"// TRASH (<10): {sum(1 for e in price_index.values() if e.estimate_fg < 10)}",
        ])
        
        return "\n".join(lines) + "\n"
