# Additional set item prices
set_items_extra:
  # Sets from the output
  telling_of_beads: 1
  hwanins_seal: 1
  hwanins_splendor: 1
  hsarus_iron_fist: 0.5
  hsarus_iron_heel: 0.5
  mcauleys_paragon: 0.5
  mcauleys_riprap: 0.5
  mcauleys_taboo: 0.5
  cleglaws_pincers: 0.5
  milabregas_diadem: 0.5
  rite_of_passage: 1
  horazons_hold: 1
  berserkers_hatchet: 0.5
  najs_puzzler: 1
  isenharts_horns: 0.5
  isenharts_parry: 0.5
  warlords_conquest: 1
  warlords_lust: 1
  warlords_crushers: 1
  civerbs_cudgel: 0.5
  civerbs_ward: 0.5
  bane_wraithskin: 0.5
  bane_oathmaker: 0.5
  bane_authority: 0.5
  arctic_mitts: 0.5
  vidalas_fetlock: 0.5
  natalyas_shadow: 2
  aldurs_stony_gaze: 2
  aldurs_gauntlet: 1
  sazabis_ghost_liberator: 2
  
  # More sets
  hwanins_blessing: 2
  hwanins_justice: 2
  hwanins_refuge: 1
  hwanins_spirit: 1
  cathans_ring: 0.5
  cathans_amulet: 0.5
  cathans_mesh: 0.5
  cathans_sigil: 0.5
  cathans_rule: 0.5
  civerbs_crown: 0.5
  civerbs_glyph: 0.5
  civerb_scepter: 0.5
  deaths_hand: 0.5
  deaths_guard: 0.5
  discipless_darkscale: 0.5
  discipless_dracule: 0.5
  infernal_cap: 0.5
  infernal_sign: 0.5
  infernal_mantle: 0.5
  infernal_tool: 0.5
  irathas_collar: 1
  irathas_coil: 0.5
  irathas_crown: 0.5
  irathas_cuff: 0.5
  isenharts_case: 0.5
  isenharts_horn: 0.5
  isenharts_light: 0.5
  isenharts_parasol: 0.5
  milabregas_crown: 0.5
  milabregas_jewel: 0.5
  milabregas_orb: 0.5
  milabregas_rod: 0.5
  milabregas_weave: 0.5
  orphan_hat: 0.5
  orphan_robe: 0.5
  sanders_cap: 0.5
  sanders_folly: 0.5
  sanders_riparian: 0.5
  sanders_stout_nag: 0.5
  sanders_taboo: 0.5
  sigon_gauntlets: 1
  sigon_girdle: 0.5
  sigon_helm: 0.5
  sigon_shelter: 0.5
  sigon_sabot: 0.5
  tancreds_horn: 0.5
  tancreds_hobnails: 0.5
  tancreds_skull: 0.5
  tancreds_spine: 0.5
  tancreds_weird: 0.5
  vidalas_amulet: 0.5
  vidalas_barb: 0.5
  vidalas_lock: 0.5
  vidalas_ambush: 0.5
  wilhelms_face: 0.5
  wilhelms_pride: 0.5
  dark_adhesion: 0.5
  trade_vise: 0.5
  sash_of_the_damned: 0.5
  boosted_brethren: 0.5

# Misc item prices (potions, scrolls, etc)
misc_prices:
  healing_potion: 0
  mana_potion: 0
  rejuvenation_potion: 0.1
  full_rejuvenation_potion: 0.3
  stamina_potion: 0
  antidote_potion: 0
  thawing_potion: 0
  scroll_of_identify: 0
  scroll_of_town_portal: 0
  tome_of_identify: 0.5
  tome_of_town_portal: 0.5
  arrow: 0
  bolt: 0
  key: 0.1
  gold: 0
  elixir: 0.5
  crafting_material: 0.5
