# Extended unique and base prices
# Properly formatted YAML

unique_low:
  shadowfang: 0.5
  the_atlantian: 0.5
  blacktongue: 0.5
  griswolds_edge: 0.5
  soulflay: 0.5
  frostwind: 0.5
  ginthers_rift: 1
  coldsteel_eye: 1
  bing_sz_wang: 0.5
  swordguard: 1
  ripsaw: 0.5
  executioners_justice: 2
  the_diggler: 0.5
  irices_shard: 0.5
  bloodletter: 1
  headstriker: 2
  fleshripper: 2
  deathspade: 0.5
  bladebone: 0.5
  goreshovel: 0.5
  the_humongous: 0.5
  butchers_pupil: 1
  spellsteel: 0.5
  runemaster: 1
  hellslayer: 1
  messerschmidts_reaver: 1
  deaths_cleaver: 10
  felloak: 0.5
  bloodrise: 0.5
  dark_clan_crusher: 0.5
  sureshrill_frost: 0.5
  earthshaker: 0.5
  the_gavel: 0.5
  schaefers_hammer: 10
  stormlash: 15
  horizonstornado: 1
  baranar_star: 5
  dimoaks_hew: 0.5
  blackleach_blade: 0.5
  husoldal_evo: 0.5
  kelpie_snare: 1
  athenas_wrath: 0.5
  stormspire: 3
  tomb_reaver: 30
  wraithflight: 0.5
  ichorsting: 0.5
  piercerib: 0.5
  skystrike: 0.5
  witchwild_string: 3
  endlesshail: 0.5
  demon_machine: 1
  gutsiphon: 0.5
  hellrack: 2
  langer_briser: 0.5
  cliffkiller: 1
  eaglehorn: 5
  windforce: 15
  lycanders_aim: 2
  kuko_shakaku: 2
  buriza_do_kyanon: 3
  doomslinger: 0.5
  the_scalper: 0.5
  deathbit: 0.5
  gimmershred: 3
  demons_arch: 2
  titans_revenge: 8
  thunderstroke: 15
  gull: 1
  wizardspike: 3
  gravenspine: 0.5
  suicidewand: 1
  arm_of_king_leoric: 8
  deaths_web: 50
  the_salamander: 0.5
  chromatic_ire: 0.5
  lazarus_spire: 0.5
  ondals_wisdom: 2
  mang_songs_lesson: 1
  the_oculus: 3
  occy: 3
  deaths_fathom: 30
  fathom: 30
  eschutas_temper: 15
  tal_rashas_lidless_eye: 10
  zakarums_hand: 3
  hand_of_blessed_light: 2
  pelta_lunata: 0.5
  sparkmail: 0.5
  goldskin: 2
  ironpelt: 2
  the_spirit_shroud: 1
  twitchthroe: 1
  victors_silk: 0.5
  venomsward: 0.5
  skin_of_the_flayed_one: 1
  atmas_wail: 1
  black_hades: 1
  duriels_shell: 2
  shaftstop: 3
  skullders_ire: 5
  vipermagi: 5
  spiritforge: 3
  crow_caw: 2
  toothrow: 1
  rockfleece: 1
  arkaines_valor: 3
  tyraels_might: 5
  ormus_robes: 5
  war_bonnet: 0.5
  tarnhelm: 0.5
  biggins_bonnet: 0.5
  coif_of_glory: 0.5
  howltusk: 0.5
  dark_sight_helm: 1
  wormskull: 1
  duskdeep: 1
  undead_crown: 1
  rockstopper: 2
  peasant_crown: 2
  stealskull: 2
  blood_spirit: 1
  demonhorns_edge: 1
  arreats_face: 8
  jalals_mane: 5
  vampire_gaze: 5
  giant_skull: 3
  crown_of_ages: 15
  harlequin_crest: 8
  shako: 8
  griffons_eye: 80
  nightwings_veil: 30
  valkyrie_wing: 5
  kiras_guardian: 8
  steelshade: 3
  andariels_visage: 5
  wall_of_the_eyeless: 0.5
  sigons_cover: 1
  blade_barrier: 1
  spike_thorn: 1
  lance_guard: 1
  herald_of_zakarum: 10
  alma_negra: 5
  medusas_gaze: 5
  tiamats_rebuke: 2
  stormshield: 10
  lenymo: 0.5
  nightsmoke: 1
  snakecord: 0.5
  bladebuckle: 0.5
  goldwrap: 2
  razortail: 3
  string_of_ears: 3
  tal_rashas_fine_spun_cloth: 5
  snowclash: 2
  thundergods_vigor: 5
  verdungos_hearty_cord: 8
  arachnid_mesh: 15
  nosferatus_coil: 5
  hotspur: 0.5
  goblin_toe: 0.5
  treads_of_cthbon: 0.5
  gorefoot: 0.5
  tearhaunch: 1
  infernostride: 2
  waterwalk: 3
  silkweave: 2
  war_traveler: 8
  gore_rider: 5
  marrowwalk: 5
  sandstorm_trek: 8
  shadow_dancer: 8
  the_hand_of_broc: 0.5
  bloodfist: 1
  chance_guards: 3
  magefist: 3
  frostburn: 3
  venom_grip: 1
  lava_gout: 1
  hellmouth: 1
  laying_of_hands: 3
  steelrend: 5
  draculs_grasp: 8
  nagelring: 0.5
  manald_heal: 0.5
  ring_of_engagement: 1
  stone_of_jordan: 8
  raven_frost: 5
  dwarf_star: 3
  carrion_wind: 5
  natures_peace: 5
  wisp_projector: 40
  bul_kathos_wedding_band: 8
  nokozan_relic: 0.5
  angelic_wings: 1
  tancreds_crow: 0.5
  saracens_chance: 2
  the_cats_eye: 5
  highlords_wrath: 8
  maras_kaleidoscope: 15
  atmas_scarab: 3
  seraphs_hymn: 5
  blackbogs_sharp: 0.5
  jade_talon: 3
  bartucs_cutthroat: 3
  shadow_killer: 2
  firelizards_talons: 2
  cerebus: 1
  spiritkeeper: 1
  wolfhowl: 2
  homunculus: 5
  boneflame: 5
  darkforge_spawn: 3

base_prices:
  thresher: 25
  giant_thresher: 30
  colossus_voulge: 15
  cryptic_axe: 8
  great_poleaxe: 10
  scythe: 1
  poleaxe: 1
  voulge: 0.5
  bill: 0.5
  bec_de_corbin: 1
  fuscina: 0.5
  ceremonial_pike: 0.5
  brandistock: 0.5
  spear: 0.5
  pike: 0.5
  halberd: 0.5
  bardiche: 0.5
  grim_scythe: 2
  phase_blade: 15
  crystal_sword: 8
  dimensional_blade: 5
  balrog_blade: 10
  legendary_sword: 8
  colossus_blade: 10
  colossus_sword: 8
  champion_sword: 5
  conquest_sword: 3
  cryptic_sword: 3
  mythic_sword: 3
  rune_sword: 1
  ancient_sword: 1
  executioner_sword: 2
  two_handed_sword: 0.5
  claymore: 0.5
  bastard_sword: 0.5
  broad_sword: 0.5
  battle_sword: 0.5
  long_sword: 0.5
  gladius: 0.5
  short_sword: 0.5
  falchion: 0.5
  cutlass: 0.5
  dirk: 0.5
  dagger: 0.5
  berserker_axe: 20
  silver_edged_axe: 8
  ettin_axe: 5
  champion_axe: 5
  glorious_axe: 3
  decapitator: 3
  naga: 2
  military_pick: 1
  war_axe: 1
  large_axe: 0.5
  broad_axe: 0.5
  battle_axe: 0.5
  great_axe: 0.5
  giant_axe: 0.5
  bearded_axe: 1
  tabar: 1
  gouge: 0.5
  spike: 0.5
  tomahawk: 0.5
  caduceus: 10
  scourge: 5
  legendary_mallet: 8
  thunder_maul: 5
  ogre_maul: 3
  martel_de_fer: 2
  great_maul: 2
  war_hammer: 1
  maul: 0.5
  sledgehammer: 0.5
  flanged_mace: 0.5
  morning_star: 0.5
  cudgel: 0.5
  club: 0.5
  truncheon: 0.5
  war_scepter: 3
  divine_scepter: 5
  might_scepter: 3
  hydra_bow: 8
  crusader_bow: 5
  grand_matron_bow: 5
  matriarchal_bow: 3
  blade_bow: 3
  edge_bow: 2
  shadow_bow: 2
  great_bow: 2
  gothic_bow: 2
  battle_bow: 1
  long_war_bow: 0.5
  short_war_bow: 0.5
  long_bow: 0.5
  short_bow: 0.5
  composite_bow: 0.5
  double_bow: 1
  cedar_bow: 1
  colossus_crossbow: 3
  demon_crossbow: 2
  chu_ko_nu: 1
  arbalest: 1
  ballista: 2
  siege_crossbow: 1
  heavy_crossbow: 0.5
  light_crossbow: 0.5
  crossbow: 0.5
  monarch: 8
  sacred_targe: 15
  sacred_rondache: 12
  kurast_shield: 10
  vortex_shield: 12
  zakarum_shield: 5
  gilded_shield: 3
  heraldic_shield: 2
  crown_shield: 2
  akaran_targe: 3
  akaran_rondache: 2
  defender: 0.5
  round_shield: 0.5
  kite_shield: 0.5
  tower_shield: 1
  pavise: 1
  luna: 5
  hyperion: 3
  aegis: 2
  ward: 2
  archon_plate: 15
  dusk_shroud: 12
  wyrmhide: 8
  scarab_hull: 5
  wire_fleece: 8
  great_hauberk: 10
  balrog_skin: 8
  hellforge_plate: 5
  kraken_shell: 5
  sacred_armor: 5
  shadow_plate: 3
  lacquered_plate: 2
  ornate_plate: 2
  chaos_armor: 2
  ancient_armor: 1
  full_plate_mail: 1
  plate_mail: 0.5
  field_plate: 0.5
  gothic_plate: 1
  scale_mail: 0.5
  chain_mail: 0.5
  breast_plate: 0.5
  light_plate: 0.5
  studded_leather: 0.5
  leather_armor: 0.5
  quilted_armor: 0.5
  mage_plate: 20
  diadem: 10
  tiara: 8
  coronet: 5
  circlet: 3
  corona: 8
  shako: 5
  spired_helm: 3
  demonhead: 3
  death_mask: 2
  bone_visage: 2
  grim_helm: 2
  casque: 2
  sallet: 2
  avenger_guard: 2
  slayer_guard: 3
  hunter_guise: 2
  wolf_head: 1
  spirit_mask: 1
  suwayyah: 15
  runic_talons: 15
  scissors_suwayyah: 12
  greater_talons: 12
  feral_claws: 8
  greater_claws: 5
  hand_scythe: 3
  wrist_spike: 3
  quhab: 2
  scissors_quhab: 2
  blade_talons: 5
  katar: 1
  wrist_sword: 2
  hatchet_hands: 2
  cestus: 2
  battle_cestus: 3
  fury_visor: 2
  destroyer_helm: 2
  conqueror_crown: 2
  guardian_crown: 2
  raging_helm: 1
  fury_band: 1
  sky_spirit: 2
  sun_spirit: 2
  earth_spirit: 2
  alpha_helm: 2
  totemic_mask: 2
  antlers: 1
  wolf_pelt: 1
  hawk_helm: 1
  hierophant_trophy: 3
  cantor_trophy: 2
  succubus_skull: 3
  bloodlord_skull: 3
  zombie_head: 2
  death_mask_head: 1
  dimensional_shard: 5
  swirling_crystal: 2
  champion_orb: 2
  eldritch_orb: 2
  metallic_orb: 1
  glowing_orb: 1
  crystal_orb: 1
  lich_wand: 10
  unearthed_wand: 15
  grave_wand: 3
  tomb_wand: 3
  burntwand: 2
  polished_wand: 1
  yew_wand: 1
  wand: 0.5
  bone_wand: 1
  grim_wand: 1
